### ISSUE TITLE
Prune does not delete data from storage unless exhaustive option set

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#122]
notes: 
- i have 2 repositories with the same data and the same number of revisions, and both have the same storage destination. for both repo i run this at the same time.

last revision is 7
d = duplicacy (faster to write)
rev 6 contains 10 gb
rev  7 contains only 1 gb of data
total storage size 10 gb 
total repo size 11 GB (i just copy-pasted a folder)

command: d prune -r 1-6
- the revisions are deleted (as per d list)
- at this point i expect that everything is deleted and storage has size 1 GB, but instead storage still has size 10GB

d prune -exhaustive
- now storage has size 1GB as expected.

question: shouldn't exhaustive be used by default? If not, could you please explain why?
note that i never used -exclusive, since i have 2 repos.

**Comment by gilbertchen** [comment]
You can use -exclusive with multiple repos, as long as there aren't any backups that are still running (or going to run).

The -exhaustive option will do a recursive list on the chunks directory on the remote storage and remove any file that doesn't look like a chunk file.  It can be slow.  If -exhaustive is not provided, Duplicacy will only look at all chunk files referenced by any snapshot.

I think in your case the first time it didn't release the space because it only renamed chunks to fossils according to the [two-step fossil collection algorithm](https://github.com/gilbertchen/duplicacy/blob/master/DESIGN.md).  It should be safe to use the -exclusive option to immediately delete them.

**Comment by TheBestPessimist** [comment]
Problem is i ran the prune command 2 times in each of the 2 repos, before trying with the -exhaustive, and the old unreferenced (in my opinion) chunks were not cleaned from the storage.

**Comment by TheBestPessimist** [comment]
Closing this as i don't seem to have this problem anymore.
User error maybe?
