### ISSUE TITLE
Is this a Hubic or Duplicacy bug?

### ISSUE THREAD

**Issue by nikjft** [gilbertchen/duplicacy#162]
I'm repeatedly getting these errors when uploading to Hubic after a few chunks have successfully uploaded.

`2017-09-06 09:21:42.445 ERROR UPLOAD_CHUNK Failed to upload the chunk 9816b1610a78bc125574c4b6596ecdec5f3f2b038617759d1e1a14c074268e5e: Put https://lb1040.hubic.ovh.net/v1/AUTH_xxxxxxx/default/duplicacy/chunks/9816b1610a78bc125574c4b6596ecdec5f3f2b038617759d1e1a14c074268e5e: net/http: timeout awaiting response headers`

**Comment by jt70471** [comment]
My guess is it's either a network issue or a Hubic problem. How frequently do you receive these errors?

**Comment by gilbertchen** [comment]
I already increased the timeout values for the Hubic backend in https://github.com/gilbertchen/duplicacy/commit/b4f314227511e14ee7bf42cbdbf9d75708568f11.  Their servers' performance is horrible, mostly because they do not reuse the http connections and every request has to start with a new round of https negotiations.

**Comment by nikjft** [comment]
You aren't kidding about horrible. Was looking at a 4 day upload to Hubic over a fast connection, same backup to B2 is estimated at 9 hours. Thinking that may be worth the extra few bucks a month for storage.
