### ISSUE TITLE
Memory Issue on Raspberry Pi

### ISSUE THREAD

**Issue by neilmusgrove** [gilbertchen/duplicacy#201]
Hi. Firstly great software, it ticks all the boxes for me. I'm running it on a raspberry pi (one of the older versions) which I use as an SMB NAS. When backing up, everything progresses nicely for a while until the process crashes with an out-of-memory exception. I appreciate the pi doesn't have a lot of memory but it seems quite logical to run Duplicacy on low-spec NAS type devices so they can auto-backup. Once the process has crashed I can restart it and it will continue which makes me think that it's either a memory leak or something which could be resolved with optimisation for low memory devices. I've attached the relevant section of the output, let me know if I can help by providing any debug information. One thing I tried was reducing the upload threads to 1 from 2 but this had no effect. Thanks.
Version 2.0.9 for Arm.
[log.txt](https://github.com/gilbertchen/duplicacy/files/1313491/log.txt)

**Comment by gilbertchen** [comment]
The stack trace shows that the memory ran out when Duplicacy tried to allocate a 16MB buffer, which is the maximum buffer size for the default average chunk size of 4MB.  If you decrease the average chunk size to 1 MB (by running `init -c 1m` with a new storage), then the maximum buffer size would be 4 MB, and that may save some memory.

You can also set the environment variable DUPLICACY_ATTRIBUTE_THRESHOLD to 1 -- this will remove all extended attributes from the memory when indexing the repository directory.  They will be read again and uploaded when uploading the snapshot file as the last step of the backup.

If these two tricks still do not solve the issue, maybe you can try to increase the swap memory: https://www.bitpi.co/2015/02/11/how-to-change-raspberry-pis-swapfile-size-on-rasbian/.

**Comment by tbain98** [comment]
@gilbertchen Can you provide a rough estimate of how many of those buffers exist within Duplicacy, so we can get a rough estimate of how much difference changing their size should make? It would be helpful to know if there are 1 or 10 or 100, and to know if there are 1 or 10 per thread (or per any other multiplier).

@neilmusgrove I'm running on an ODroid C2 with 2GB of RAM. I'm about 24 hours into my third attempt at an initial backup of a 200GB repository, and I'm using 780MB reserved memory and 1.1GB virtual memory. I'm using 16 threads and an average chunk size of 2MB, and I'm not using DUPLICACY_ATTRIBUTE_THRESHOLD=1.

Be aware that setting a Raspberry Pi to swap to the SD card will result in significantly more writes to the card, which could cause it to fail sooner. If you have a locally-attached spinning hard drive, make sure you set up to swap there instead of the SD card.

**Comment by neilmusgrove** [comment]
Thanks both, I tried DUPLICACY_ATTRIBUTE_THRESHOLD=1 last night and it didn't solve the issue but it seemed to last longer before failing (I can't be sure). I'm going to try the swap next and I will set swap to the HDD, I guess this will resolve the issue. I'm not eager to try changing the chunk size since I don't want to go through the initial backup of a large quantity of data again. I think there is only 512mb of memory on the pi (it's an earlier model) so it's not a lot but it chugs away quite happily for a few hours before crashing.

**Comment by gilbertchen** [comment]
Each uploading threads may use two chunk buffers, one for raw chunk data and the other for compressed and encrypted data.  Plus there is a reading thread that performs pack-and-split on files to create raw chunks.  Therefore, there can be at most `2*n+1` chunk buffers, where `n` is the number of uploading threads.

**Comment by tbain98** [comment]
@gilbertchen That's great info, thanks. That means that the number of threads should affect memory usage (despite what @neilmusgrove observed in the original description), and that the size of the chunks should also affect it.

It also means that for my initial uplod with a 2MB default chunk size (so 8MB buffers) and 16 upload threads, buffers were consuming 264MB of RAM out of the ~780MB total that I observed.

**Comment by neilmusgrove** [comment]
Having implemented most of the suggestions above I don't seem to be having any re-occurrence of the memory issue. Thanks for the assistance.
