### ISSUE TITLE
Repair "missing chunks"

### ISSUE THREAD

**Issue by RolandVor** [gilbertchen/duplicacy#234]
Hi!

I am looking into duplicacy as a replacement of CrashPlan and I have to say: I am impressed!

I have one scenario so far which I don't see an obvious solution for yet (it hasn't happened to me, I just want to know what to do in this situation): If a chunk is missing / corrupted, I'd like to fix the problem by regenerating new chunks from all affected files which touch the corrupted chunk. In another issue I read about deleting snapshots and pruning afterwards, but let's assume every snapshot references the missing chunk.

Theoretically I guess I could look up which files are affected by the corrupted chunk and manually change the timestamp such that duplicacy interprets them as "changed" since last backup and re-backups them. Would this work and is there an automatic way to repair corrupt states by re-backuping files which I still have in the original repository?

**Comment by RolandVor** [comment]
Writing about it just gave me a better understanding and a possible solution maybe (sorry then for the spam). If I delete all snapshots and reissue a "backup", duplicacy should just regenerate the missing chunks and skip all other ones which exists already... That seems to work.

**Comment by TheBestPessimist** [comment]
A question: why is it needed to delete the snapshots? why not just do the new backup? (That's what i would do, but probably @gilbertchen  can explain us better).

**Comment by gilbertchen** [comment]
That is because Duplicacy always uses the latest snapshot as the base (by creating a cache containing all chunks referenced by the latest snapshot).  Chunks that exist in the cache will not be uploaded.  Therefore, if the latest snapshot contains the missing chunk then Duplicacy will think it exists in the storage too and will not regenerate it.

Deleting all snapshots is one way to force it to regenerate the missing chunk.  Another way is to use a new repository id (by editing the `.duplicacy/preferences` file).  I also think we should add a `-no-cache` option to the backup command.

**Comment by TheBestPessimist** [comment]
What about the check command?

**Comment by gilbertchen** [comment]
The check command only checks if chunks exist in the storage -- it doesn't regenerate missing chunks.

**Comment by RolandVor** [comment]
Your explanation makes sense :) ! Thanks a lot!
