### ISSUE TITLE
Question about "Lock-Free-Deduplication"

### ISSUE THREAD

**Issue by wrfly** [gilbertchen/duplicacy#282]
Hello there, I'm not clear about this part in [Lock-Free-Deduplication](https://github.com/gilbertchen/duplicacy/wiki/Lock-Free-Deduplication)

> Instead, to check if a chunk has already been uploaded before, one can just perform a file lookup via the file storage API using the file name derived from the hash of the chunk.

If you eliminate the chunk indexing database, how can the `file storage API` knows whether the chunk has already been uploaded before?

Can you tell me the difference between the `chunk indexing database` and the `file storage API`?

Thanks.

**Comment by gilbertchen** [comment]
By `file storage API` I meant a lookup API that can tell if a file with the given name exists or not.  So once we have a chunk locally, we can calculate the hash, and then derive a file name from the hash, and use the file name to look up if the chunk already exists in the storage.

**Comment by wrfly** [comment]
So **there is** a database that stores `file name` & `chunk` pairs, right?

**Comment by Fonant** [comment]
No, a database is not needed because the filename is simply a hash of the chunk data. Another chunk from a different machine with exactly the same data will result in the same filename when that data is hashed.

1. Hash the chunk data: this gives you the filename.
2. Ask the storage whether that file exists or not.
3. If it exists, don't upload it again: storage deduplicated, and time saved!
4. If it doesn't exist, upload with a temporary name then rename when finished.

Any other process, from any machine, uploading the same chunk of binary data will calculate the same hash filename. So cross-machine deduplication is achieved without any shared database and without any explicit locking mechanism. Very clever and very simple.

**Comment by wrfly** [comment]
Hello @Fonant , thanks for your answer. But I'm still curiosity about `Ask the storage whether that file exists or not.`

If I ask the storage, is that means the `storage` contains all the metadata and equals to the `database`? We just put the calculation in our local machine rather than the remote server, right?

**Comment by Fonant** [comment]
Well, yes, you could consider the storage files to be simultaneously the stored data and the database of what is stored - as the filenames of the stored data are the hashes of the stored data. The "lock" for a particular chunk of data is the existence, or not, of the stored filename of the data itself. Since file systems implicitly refuse to allow two files to have the same filename, and since file systems are optimised to locate data by filename, using the hash-of-data as the filenames works to both "lock" and de-duplicate without needing a separate database. The really handy thing is that this works for data from multiple sources without any extra work, and the sources don't even need to know anything about each other.

Asking the storage whether the data is already stored is as simple as calculating the hash of that data locally, and then calling a storage file system API function like `file_exists()` or `get_file()` or `download_file()` or `list_files()`.

The stored chunk files self-document their contents using their filenames, so no separate database of filename-to-chunk pairs is needed.

**Comment by wrfly** [comment]
Thank you very much!

Before I'm closing this issue, I have another question to ask, or, discuss. 

Is there any way for this "Lock-Free-Deduplication" to backup files in multiple storage back end? One thing I can think up is that we use a master-slave system, and the slave sync data from the master(replica set). Can we use shard or something else? We don't want to put all our eggs in one basket.

Since there is only one storage back end, I'm concerned about the safety of the backups.

**Comment by Fonant** [comment]
The lock-free-deduplication is per-storage. Having multiple storages for reliability and resilience would be deliberately duplicating the backup data.

You can use Duplicacy to backup data to any number of different storages, of many different types.

You can either back up to each storage independently, or you could back up to one and use `duplicacy copy` to make an identical copy. See https://github.com/gilbertchen/duplicacy/wiki/copy

**Comment by wrfly** [comment]
Cool. Thank you~

**Comment by VsevolodGolovanov** [comment]
> 1. Hash the chunk data: this gives you the filename.
> 2. Ask the storage whether that file exists or not.
> 3. If it exists, don't upload it again: storage deduplicated, and time saved!
> 4. If it doesn't exist, upload with a temporary name then rename when finished.

Are there additional checks in place to protect against hash collisions? (I know, unlikely, but still.)
