### ISSUE TITLE
Unable to make backup to b2 after pruning

### ISSUE THREAD

**Issue by Technifocal** [gilbertchen/duplicacy#323]
Hi, first of all I'd like to preface this stating I don't need to recover the data (As I'm using `duplicacy` as a test at the moment), so don't worry if I've lost any data.

Getting onto the issue at hand, I run my backups with:

`duplicacy backup --stats --threads=16`

hourly, and prune with:

`duplicacy prune --all --exhaustive --keep 0:31 --keep 7:14 --keep 1:7`

daily. This means that both the backup and prune start at the same time at midnight, not sure if this is an issue or not (This is the first "day" after setting up my schedules, and the issue immediately occurred).

My prune logs show:
```
Marked fossil 0fa80b7c9cfeaadf049953d2dbc6add86bf2427e3c24d640f8af64ea88da010d
Marked fossil 8712e4798745f511dcc4e524cc5f621a9494855000f7e80dac89cfa391668324
Marked fossil b293fda55bf903426fbf1677011e584dfa602ce4f0c910a470466bb40c8d44a4
Marked fossil dabdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e
Fossil collection 1 saved
```

However, now, when attempting to backup, I get:

```
$ duplicacy --debug backup

Storage set to b2://duplicacy-bucket/
Reading the environment variable DUPLICACY_B2_ID
Reading b2_id from preferences
Reading the environment variable DUPLICACY_B2_KEY
Reading b2_key from preferences
Reading the environment variable DUPLICACY_B2_ID
Reading b2_id from preferences
Reading the environment variable DUPLICACY_B2_KEY
Reading b2_key from preferences
Reading the environment variable DUPLICACY_PASSWORD
Reading password from preferences
Using 16384 iterations for key derivation
URL request 'https://f001.backblazeb2.com/file/duplicacy-bucket/nesting' returned status code 404
URL request 'https://f001.backblazeb2.com/file/duplicacy-bucket/nesting' returned status code 404
b2_download_file_by_name did not return headers
Chunk read levels: [1], write level: 1
Compression level: 100
Average chunk size: 16777216
Maximum chunk size: 67108864
Minimum chunk size: 4194304
Chunk seed: <<REDACTED>>
Reading the environment variable DUPLICACY_PASSWORD
Reading password from preferences
top: /home/user, quick: true, tag: 
Downloading latest revision for snapshot snapshot-id
Listing revisions for snapshot snapshot-id
Loaded file snapshots/snapshot-id/31 from the snapshot cache
URL request 'https://f001.backblazeb2.com/file/duplicacy-bucket/chunks/da/bdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e' returned status code 404
URL request 'https://f001.backblazeb2.com/file/duplicacy-bucket/chunks/da/bdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e' returned status code 404
b2_download_file_by_name did not return headers
Chunk dabdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e has been marked as a fossil
URL request 'https://f001.backblazeb2.com/file/duplicacy-bucket/chunks/da/bdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e.fsl' returned status code 404
Failed to download the chunk dabdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e: http: read on closed response body
```

Check gets me:

```
$ duplicacy check --all
Storage set to b2://duplicacy-bucket/
Listing all chunks
All chunks referenced by snapshot snapshot-id at revision 1 exist
All chunks referenced by snapshot snapshot-id at revision 6 exist
All chunks referenced by snapshot snapshot-id at revision 7 exist
All chunks referenced by snapshot snapshot-id at revision 8 exist
All chunks referenced by snapshot snapshot-id at revision 9 exist
All chunks referenced by snapshot snapshot-id at revision 10 exist
All chunks referenced by snapshot snapshot-id at revision 11 exist
All chunks referenced by snapshot snapshot-id at revision 12 exist
All chunks referenced by snapshot snapshot-id at revision 13 exist
All chunks referenced by snapshot snapshot-id at revision 14 exist
All chunks referenced by snapshot snapshot-id at revision 15 exist
All chunks referenced by snapshot snapshot-id at revision 16 exist
All chunks referenced by snapshot snapshot-id at revision 17 exist
All chunks referenced by snapshot snapshot-id at revision 18 exist
All chunks referenced by snapshot snapshot-id at revision 19 exist
All chunks referenced by snapshot snapshot-id at revision 20 exist
All chunks referenced by snapshot snapshot-id at revision 21 exist
All chunks referenced by snapshot snapshot-id at revision 22 exist
All chunks referenced by snapshot snapshot-id at revision 23 exist
All chunks referenced by snapshot snapshot-id at revision 24 exist
All chunks referenced by snapshot snapshot-id at revision 25 exist
All chunks referenced by snapshot snapshot-id at revision 26 exist
All chunks referenced by snapshot snapshot-id at revision 27 exist
All chunks referenced by snapshot snapshot-id at revision 28 exist
All chunks referenced by snapshot snapshot-id at revision 29 exist
All chunks referenced by snapshot snapshot-id at revision 30 exist
Failed to download the chunk b293fda55bf903426fbf1677011e584dfa602ce4f0c910a470466bb40c8d44a4: http: read on closed response body
```

Same (identical) output with `duplicacy check --all --fossils`.

If I visit backblaze directly, I see this:

![2018-01-09-012153_673x165_scrot](https://user-images.githubusercontent.com/20205745/34700522-7e547cd8-f4db-11e7-9d28-9a9ecf73fa61.png)

I realise I could probably fix this by download the chunk from b2, deleting the object in b2, and reuploading it, I'm just wondering why this is occurring and if it was my fault or a bug.

If I can provide any more files to be of assistance, feel free to ask,

Thanks!

**Comment by gilbertchen** [comment]
This is definitely a bug.  The bug is caused by the use of the `--exhaustive` option.  When this option is specified, it will scan the whole chunk directory for unreferenced chunks.  However, if there is an ongoing backup, all chunks uploaded by this backup will be marked as fossils, as the snapshot file will be uploaded only as the last step and may not be seen by the prune command.

Usually when this happens a `duplicacy check --all --fossils` command should be able to search in fossils and resolve the missing chunks.  However, there is a special type of chunks that are different then others.  These chunks store the hashes of file content chunks.  To retrieve the list of all chunks referenced by a backup, these chunks must be downloaded and decoded.  However, if the prune command fossilizes any of these chunks, then the function that returns the referenced chunk list would bail out when trying to download the one that has been made a fossil.

The fix is to always check fossils when downloading this type of chunks.  For now, I think you can, for each missing chunk reported by the check command, remove the latest version whose size is 0 bytes.  For instance, if b293fda55bf903426fbf1677011e584dfa602ce4f0c910a470466bb40c8d44a4 can't be downloaded, you should see two versions on the b2 web page just like the chunk shown in your screenshot.  Remove the first version with a size of 0 bytes.  This is equivalent to turning the fossil back into a chunk.  Hopefully there will be only a few such chunks (if your backup isn't too large).  Once `duplicacy check --all --fossils` reports no missing chunks, you can run  `duplicacy check --all --resurrect` to recover from other missing chunks.

**Comment by gilbertchen** [comment]
Should be fixed by https://github.com/gilbertchen/duplicacy/commit/771323510d8718ce58705a1d244b90e86db06ec8.

I was wrong about the behavior of the chunk download function.  It does already check if the fossil exists.  The real problem was that it tries to download the fossil directly in this case, which isn't supported by many storage backends (that is why you got the `http: read on closed response body` error).  The correct way is to resurrect the fossil (turn it back into the chunk) and then download the chunk.

I've tested the exact scenario and the fix appeared to work as expected.

**Comment by Technifocal** [comment]
@gilbertchen Thank you for getting back to me,I have just compiled from source and can validate it works as expected with a normal `duplicacy backup`:

```
Fossil dabdd5d8ec65b3f15604079969e7b6c23435ef256c990269557e0c66d669769e has been resurrected
Fossil b293fda55bf903426fbf1677011e584dfa602ce4f0c910a470466bb40c8d44a4 has been resurrected
Fossil 8712e4798745f511dcc4e524cc5f621a9494855000f7e80dac89cfa391668324 has been resurrected
```

Can I just ask before closing this issue, is running with `--exhaustive` not recommended for routine executions then, or was this 100% a bug that shouldn't have happened? For example, `--exclusive` is not recommended because it assumes no other computers are currently backing up at that time.

Thanks once again!

**Comment by gilbertchen** [comment]
Both.  You don't need to run `-exhaustive` daily.  It is only needed when you have an incomplete backup which may leave unreferenced chunks so you want to clean up the storage.  But the bug shouldn't happen even if you do this.

**Comment by Fonant** [comment]
Aha, this looks like a bug I came across. I wasn't confident with my understanding of duplicacy, so ended up deleting a lot of old revisions to get prune working again (luckily not a problem!).

Glad to hear the problem has been fixed :)

**Comment by Technifocal** [comment]
@gilbertchen Fair enough. Thank you for getting back to me.

@Fonant As am I :-)
