### ISSUE TITLE
prune usage clarification for wiki

### ISSUE THREAD

**Issue by willodactyl** [gilbertchen/duplicacy#324]
I'm a little confused on the usage/explanation of some prune options,  I hope this is the right place to ask. I'm still learning and don't have a test repo old enough to try yet.

Let's say I have 2 repositories backing up infrequently to the same location:
- **PC1_user_docs** to b2://mybucket (daily)
- **PC2_user_docs** to b2://mybucket (every 10-ish days)

For the sake of this example let's say I'm pruning frequently with some sensible -keep options.

I'm concerned the infrequent **PC2_user_docs** backup could have chunks lost during pruning. (If I deleted shared data from one repo but meant to keep it on the other. Realistically this would be unlikely, but I am trying to understand the exact behavior).

Described here at the very bottom of the prune command:
https://github.com/gilbertchen/duplicacy/wiki/prune
> For fossils collected in the fossil collection step to be eligible for safe deletion in the fossil deletion step, at least one new snapshot from each snapshot id must be created between two runs of the prune command. However, some repository may not be set up to back up with a regular schedule, and thus literally blocking other repositories from deleting any fossils. **Duplicacy by default will ignore repositories that have no new backup in the past 7 days.**

Does this mean I should never prune twice between all repositories backing up? Can I get prune to _not_ ignore stale repositories (and is this what the -all option does)?
- `duplicacy prune -all` (is PC2_user_docs still auto-ignored after 7 days?)

> It also provide an -ignore option that can be used to skip certain repositories when deciding the deletion criteria.

This sounds like a good idea if I wanted to prune stale or deprecated repos manually.
- `duplicacy prune -ignore PC2_user_docs` (is this the same as the default behavior after 7 days?)

**Comment by gilbertchen** [comment]
If you can make sure that the prune command never runs simultaneously with the backup of PC2_user_docs, then you should be fine.

If you can't enforce that, then just make sure that the backup of PC2_user_docs takes a shorter time than the interval between two consecutive prune commands.

This is because the only scenario where a chunk owned by a backup of PC2_user_docs can be deleted by a prune command is as follows:

1. The first prune command starts while there is a backup of PC2_user_docs that is still in progress
2. The first prune command starts to collect chunks it deems unreferenced and marks them as fossils; some of these chunks may be referenced by the ongoing backup of PC2_user_docs but the prune command doesn't know.
3. The first prune command saves the fossil collection and exits.  But the backup of PC2_user_docs continues to run.
4. The second prune command starts.  It loads the fossil collection saved by the first prune command and checks if there are any new backups that the first prune command didn't see.  Since the backup of PC2_user_docs hasn't finished yet, there isn't a new backup from PC2_user_docs.
5. The second prune command checks if the fossils collected by the first prune command are referenced by any new backups that appeared after the first prune command ends.  Because the last backup from PC2_user_docs was more than 7 days ago, it thinks PC2_user_docs is inactive, so it will consider only PC1_user_docs.  Those fossils are unlikely to be referenced by any backup from PC1_user_docs, so they will be permanently removed.

As you can see, you can avoid this scenario if you never run the prune command and the backup of PC2_user_docs at the same time, or if the the backup of PC2_user_docs finishes before the second prune command (in which case the second prune command will find out that the fossils collected by the first prune command are indeed needed by the latest backup from PC2_user_docs). 

Answering your other questions, `-all` means that the retention policy applies to all repositories.  `-ignore PC2_user_docs` is equivalent to marking PC2_user_docs as being inactive for 7 days.

**Comment by willodactyl** [comment]
Thanks for the quick response!

This makes sense, the potential risk is as you said: by pruning during a backup from another source and then pruning again before the backup completes. I think I misunderstood the use of `-ignore`
