### ISSUE TITLE
Copy to Cloud or 3rd Party Tools?

### ISSUE THREAD

**Issue by jonreeves** [gilbertchen/duplicacy#333]
I'm using a NAS as my main storage location for Duplicacy but want to keep a copy in the cloud (B2 or Wasabi). Initially I was thinking of using a tool like RClone to sync these files from my NAS to the cloud account, but it has to request the entire folder structure from the cloud to figure out which files to upload (a lot of API hits). I wondered if using Duplicacy's Copy command would have to do the same, or is it able to be any more efficient than a 3rd Party Sync tool?

My questions are:
- which route is likely to be most efficient in terms of API calls?
- are there any other benefits to using Duplicacy to handle this process?

**Comment by gilbertchen** [comment]
The current implementation of the Copy command lists the entire storage directory on the destination in order to determine which chunks are needed to be uploaded to the destination.  It can be modified to check for each chunk as needed, but generally it is more efficient to list all chunks at once (sometimes it is counted as only one API call).  So I think there isn't a major difference in efficiency with regard to this issue.

These are two cases I can think of where you will have to use the Copy command:

* you want to select a few backups to copy, not all of them
* the `config` files on two storages are not bit-identical (which means the chunks need to be converted by the Copy command)

**Comment by jonreeves** [comment]
I suspected it would probably need to list everything on the destination, as there isn't really another way to 'know' what is there otherwise. So as you say, its probably very similar in terms of API Calls as other tools for uploading/syncing to B2 etc...

Thanks of the two cases you outlined. I think the first one is probably enough to make it valuable to do using Duplicacy.

The only benefit I see right now with using a 3rd party tool instead, is that Duplicacy currently doesn't show Upload Speed or Progress; missing `-stats` for the `copy` function. But I see others have already mentioned that: #271.
