### ISSUE TITLE
Folder exclusion based on contained file name

### ISSUE THREAD

**Issue by tophee** [gilbertchen/duplicacy#337]
This feature request is based in this issue on the forum: https://forum.duplicacy.com/t/file-exclusion-based-on-file-attributes-folder-exclusion-based-on-contained-file-name/485?u=christoph

So, basically, the suggestion is to add a third type of line in the filter file to allow users to say: if a folder contains a file named XYZ, exclude this folder from the backup. So, for example,  `| .duplicacy_no_backup` as a filter pattern could mean: exclude folders containing a file called `.duplicacy_no_backup`.

**Comment by wscott** [comment]
Or directories containing [CACHEDIR.TAG](http://www.brynosaurus.com/cachedir/spec.html).

**Comment by tophee** [comment]
While it certainly makes sense for duplicacy to support the cachedir.tag (as a special case of a more generic solution), I don't see the benefits of limiting the feature to that specific file.

Remember that the idea is to make it easy for the user to exclude a folder "in passing" simply by creating a file with a specific name. The cachedir.tag, in contrast, is much more complicated to create (which is not a problem in its intended use, because it is meant to be machine-created). 

Consider also this (from the cachedir.tag page):

> User-friendly file managers and other directory hierarchy browsing software may also want to notice the presence of a cache directory tag in a directory, and inform the user that the contents of the directory is automatically managed and is not likely to make much sense if "browsed" directly.

**Comment by jonreeves** [comment]
> The cachedir.tag, in contrast, is much more complicated to create

I'm not familiar with it, but it looks like just a static file the content of which is the same each time, so should be simple to copy and paste that same file to whichever directories you need excluding.



**The .gitignore Route**
Alternatively you could you have a Duplicacy equivalent to `.gitignore` where the content of the file is just exclusion rules that apply from that point in the path onward. Similar to how `.htaccess` cascades to subfolders, but any subsequent ones override the inherited ones.

For example a file called `.dupignore` that contains
```
*
```
Could be placed in any folder to force all files and subfolders `*` in that path to be excluded from the backup process.



**The existing 'filters' file Route**
It would probably however make more sense to just extend the existing 'filters' caperbility so that a file like `.dupfilters` could be created and placed in any point in the path of a repository and would contain:
```
# Exclude everything
e:.*
```
Which would achieve the same, but be within keeping of how duplicacy already works. Additionally, you could override earlier rules to forcefully include items for the path the file applies to. For example:
```
# Include .sqlite Files
i:\.sqlite$

# Exclude everything else
e:.*
```

Doing it this way, would give you the flexibility and granular control over including/excluding all or a particular filetype in a particular path.

It doesn't give you the ability to manage it all from one set of rules in one file, but it sounded like you were happy having to create a file in each folder you want excluded.

**Comment by madranet** [comment]
The ability to do this would be great on OSX too, where the Finder puts those pesky invisible `.DS_Store` files in directories all over the place. The existence of these can then prevent a `restore` proceeding unless you use the `-overwrite` flag, which is something you don't usually want to do.

**Comment by TheBestPessimist** [comment]
This has been implemented via https://github.com/gilbertchen/duplicacy/pull/392. can we close it now?

**Comment by tophee** [comment]
Yes, of course.

**Comment by TheBestPessimist** [comment]
(that was a ping to gchen since only he or op can do it :D)
