### ISSUE TITLE
Regex help

### ISSUE THREAD

**Issue by TheBestPessimist** [gilbertchen/duplicacy#355]
In the [Include Exclude Patterns](../wiki/Include-Exclude-Patterns) wiki examples I can see that  for most of the strings there, the `$` character is used at the end.

From what i read, `$` is used in order to "point" to the position after the last character which is not a newline (as in `end_of_the_string`).

In my regex tests however i saw that the matches worked well even w/o the ending `$`.
eg.: `e:(?i)\.git/.*$` works just as well as `e:(?i)\.git/.*` (without `$`)

With this finally comes my question: why is there a need for the `$` character when constructing duplicacy ignore regexes.

**Comment by gilbertchen** [comment]
I think '$' is redundant, because Duplicacy calls `re.MatchString(path)` to determine if there is a match.  If it were `re.SearchString(path)` the `$` would have been significant.

**Comment by TheBestPessimist** [comment]
I don't exactly know what the difference is between the two (but i'm gonna search).

i was thinking that a difference could be when searching for some extensions `e:*\.tmp$`, but actually, even there i can't see the need for `$` as `e:*\.tmp` already matches _only_  the end of the string.

**Comment by jonreeves** [comment]
Well if your using MatchString I would presume that the `$` is actually really important. Especially if you want to anchor a particular file extension to the end of the string your trying to match.

For example
`.*\.tmp` would match `myfile.tmp.css` and `projects/personal.tmp/importantfile.doc` but `.*\.tmp$` wouldn't.

The reason `$` doesn't matter for your first example: `\.git/.*` is because its anchoring **any** or **none** characters `.*` to the end, so it is really the same as saying `.git/` at any point in the path followed by anything or nothing. That rule seems like it would also match a folder called `myfolder.git/` though which you might not want.

I'm not exactly sure how elaborate you can be in Duplicacy with your regex, but something like `^(\/)?([^\/].*\/)?(\.git\/.*)` would be a better rule for excluding paths with a `.git/` folder in it. Although someone might have a better suggestion, its not something I've tried.

Essentially you want to match for the cases where the path starts with `.git/` or `<anything-else>/.git/` or `/<anything-else>/.git/`. Where `<anything-else>` could be any character including `/` indicating multiple sub-folders.

Here is a GO playground to show it matching and excluded expected folders:
https://play.golang.org/p/DBSbn63iT1Z

Also a Regex Tester page to show it working on other examples that you can add to:
https://regex101.com/r/Kev4MY/1

You should beable to play about with adding your own paths to see what matches and what doesn't. I don't know for sure though that Duplicacy would handle this regex. All I know is GO does when using the MatchString func.

**Comment by NiJoao** [comment]
I'm trying to optimize my filters file in terms of performance, and also readability.
Isn't `(^|/)\.git/` a possible simpler solution to "excluding paths with a .git/ folder in it"?

And correct me if I'm wrong, but the folders are tested first, and their children are only listed and tested if the parent wasn't excluded, which implies that all of the following exclusions (not inclusions) do the same, since nothing inside `folder/` will be tested.
`(^|/)folder/`
`(^|/)folder/$` 
`(^|/)folder/.*`
`(^|/)folder/.*$`

Also, if duplicacy uses MatchString, shouldn't we avoid terminating the Regex with `.*` ? It's useless, confusing, and possibly slower.

I'm working on improving the global filter file created by TheBestPessimist, and make it include files of local email clients (thunderbird, live mail, outlook, etc) and Chrome profiles.

In CP I was using this exclude regex:
`(?i).:/Users/[ \w\.]+/AppData/(?!(Local|Roaming)/(Google/Chrome/User Data|Microsoft/Outlook|Microsoft/Windows Mail|Microsoft/Windows Live Mail|Thunderbird/Profiles)).*`

In Duplicati I used:
```
-[.:\\Users\\[ \w\.]+\\AppData\\(?!(Local|Roaming)\\).+]
-[.:\\Users\\[ \w\.]+\\AppData\\[^\\]*\\(?!(Google|Microsoft|Thunderbird)\\).+]
-[.:\\Users\\[ \w\.]+\\AppData\\[^\\]*\\[^\\]*\\(?!(Chrome|Outlook|Windows Mail|Windows Live Mail|Profiles)\\).+]
```

In Duplicacy I'm thinking on doing:
```
# Include the AppData folder but nothing inside, and select subfolders one level at a time
i:/AppData/$
i:/AppData/(Local|Roaming)/$
i:/AppData/(Local|Roaming)/(Google|Microsoft|Thunderbird)/$

# Include all files+folders under the last ones
i:/AppData/(Local|Roaming)/(Google|Microsoft|Thunderbird)/(Chrome|Outlook|Windows Mail|Windows Live Mail|Profiles)/

# exclude all files not included before
e:/AppData/
```
which is equivalent to:
```
i:/AppData/($|(Local|Roaming)/)($|(Google|Microsoft|Thunderbird)/)($|(Chrome|Outlook|Windows Mail|Windows Live Mail|Profiles)/)
e:/AppData/
```

What do you guys think is the best solution in terms of performance and readability?
- Few regex rules but complicated, like my CP solution with negative lookaheads, etc.
- Many but simpler regex rules.
- Avoiding regex altogether and use simple include/excludes folders.

**Comment by TheBestPessimist** [comment]
@jonreeves holy balls that .gitignore regex looks ugly. 
I will have to do more tests, but it looks better than what we have now.
@gilbertchen, we should modify the wiki to contain the corrected variant?

@NiJoao 

> What do you guys think is the best solution in terms of performance and readability?

- From my point of view, the simpler the regex is, the better. Regex seems difficult and cryptic to begin with. I like to have the one per line, eventually with a comment before the regex to mention its quirks or motivation/needs.

I will have to try your .gitignore regex as well. I also want to check your `<other>` ignore rules

**Comment by jonreeves** [comment]
> Isn't (^|/)\.git/ a possible simpler solution to "excluding paths with a .git/ folder in it"?

@NiJoao it's shorter regex for sure, but I think it becomes more inefficient the longer the path string gets. Although I don't know if this is the same for GO as it is for Python. For example if you take a path like: `/Users/Name/Personal/Code/example.com/project/.git/myfile` the regex engine has to take 33 steps using `^(/)?([^/].*/)?(\.git/.*)` no matter what the length of the string is. However it will take 159 steps using `(^|/)\.git/` and that number will increase if the path gets longer. Infact it will increase by 3 steps for every character in the path and 5 for every folder slash.

All of that said I doubt it would have that much of an impact on performance, but its just force of habit to be more explicit when you can.

> Also, if duplicacy uses MatchString, shouldn't we avoid terminating the Regex with .* ? It's useless, confusing, and possibly slower.

Well this is where I contradict myself a bit. Despite adding inefficiency, for me, the `.*`at the end makes the regex more readable. It just clearly implies that you are saying match the Folder and Any files below it. If you weren't aware of how Duplicacy handles Matches, this should make you certain it will work the way you expect. How much more inefficient is it... it adds 1 step. Personally, that's a sacrifice worth having for the extra legibility and re-usability. But its a fair point to say its redundant in this usecase.

I mention re-usability because a regex rule should really be something you need to write once and can use anywhere (text editors, os operations, etc..). Having the `.*` allows you to match whole File Paths and not just the Folder, which is likely to be a lot more useful in other usages.

**Comment by NiJoao** [comment]
@jonreeves Very valid points!
I wasn't looking at the number of steps required, but yeah, my solution requires 3-steps per character...
Your solution has a constant step count due to `.*` being greedy, jumping immediately to the end of string and analyzing backwards. If the string after the `/.git/` increases, the steps increase.
Luckly, almost every folder-parsing app analyzes one folder at a time, recursing to subfolders if they are not excluded, and thus the matching folder (e.g.: `/.git/` ) is always at the end of the string.

And I agree, we should make Regex as generalizable as possible.
With these suggestions, I propose this solution:
`^(.*\/)?\.git\/.*`
Which takes 20 steps and should support all apps (that use '/' as folder delimiter) and regex methods (the whole path is matched).
The "?" is required to match 'duplicacy_repo_root/.git/'.

I'll improve my set-it-and-forget-it-at-your-grandmothers-PC-with-low-storage-requirements filter file and share it here.

**Comment by TheBestPessimist** [comment]
Guys, you lost me in this discussion (especially at the "so many steps" part). I don't even know what to ask or where to begin with the questions. 

I'll test all regexes and try to understand them by myself...

A first question is though why do you always use `\` (escape character) in front of `/` (folder delimiter)? From my understanding since we use raw string literals([this](https://golang.org/ref/spec#String_literals), and [this](https://stackoverflow.com/a/6770913) ) there's no need for all that escaping.

**Comment by NiJoao** [comment]
Sorry for the confusion.
Required steps are a [good approximation of the performance of a Regex pattern](https://stackoverflow.com/questions/41447805/what-are-steps-in-regexbuddy).
Many testers inform you of the number of steps required, such as: https://regex101.com/r/LMtEx5/1

Regarding the `\/`:
`/` is typically a delimiter character (e.g.: by regex101.com by default).
Duplicacy doesn't require `/` to be escaped, but supports it, and escaped regex are more generalized (e.g.: to copy paste into regex101.com).

**Comment by TheBestPessimist** [comment]
>    With these suggestions, I propose this solution:
>    `^(.*\/)?\.git\/.*`
Right now, i am using `(?i)/\.git/`, and although it is slower i think it works quite nicely and more importantly (for me at least): it looks simpler!
Here's an example: https://regex101.com/r/Kev4MY/3.

_________________________________

Regarding the `\/` vs `/`: at least on https://regex101.com, if i change the language to golang, everything looks good enough, so i would rather get rid of `\`. (again: for simplicity!).

With this i'll close this issue and show you my work from #311!

Thanks for the regex lessons!
