### ISSUE TITLE
Despite VSS: Failed to read 0 bytes: The process cannot access the file because another process has locked a portion of the file.

### ISSUE THREAD

**Issue by DreamFlasher** [gilbertchen/duplicacy#420]
duplicacy crashes for me with

```
Failed to read 0 bytes: read ...\Duplicacy\config/.duplicacy\shadow\\...\Duplicacy\config/c/Users/.../AppData/Roaming/Signal/IndexedDB/file__0.indexeddb.leveldb/LOCK: The process cannot access the file because another process has locked a portion of the file.
```

Signal was indeed open and running -- but I am using the -vss option (as can be seen in the "shadow" part of the path). It's strange that a file still can be locked, but at least duplicacy should not crash.

**Comment by gilbertchen** [comment]
This is the same issue as #309.

I think at least in this case Duplicacy can skip the locked file just like how it handles files that can't be opened, because it hasn't read any bytes yet when the error occurs.  If the error occurs after some bytes have been read then Duplicacy has no choices other than exiting immediately since it would be hard to roll back the state of the file reader.

**Comment by DreamFlasher** [comment]
Yes, it's a duplicate.
