### ISSUE TITLE
Keep timestamps on bit-identical copy command

### ISSUE THREAD

**Issue by NiJoao** [gilbertchen/duplicacy#451]
I have duplicacy backing up to a storage every 2 hours, and during the night it "duplicacy copy" to a bit-identical offsite location.
Due to several factors like unavailability, connection down, changing offsite storage location, etc, both storages can become quite out-of-sync.

Recently I resorted to free-file-sync (rsync'ish for windows) as a way to sync 400GB faster than using the copy command.
Then I noticed the app complained a lot about the chunks having different modified/created timestamps on both sides, and I had to tweak the settings to ignore timestamps.

If in a bit-identical storage, the chunks are effectively the same bitwise, wouldn't it be logical to keep the original timestamps?
It's the decision between providing the information of:
- When the file was first created in the storage, vs
- When it was created during backup.
 
I prefer the latter, but understand both.

Or better yet, preserve both info by setting Creation Time to the original creation on backup, and Modification Time to the storage-specific creation/modification.

**Comment by gilbertchen** [comment]
The timestamps of the chunk files are not part of the design, partly because most cloud storages do not store timestamps, and partly because the timestamps are insignificant (as opposed to the names of the chunk files).  It is possible to pass timestamps between storages that support them during a copy, but I think it would only increase the complexity without adding too much value.
