### ISSUE TITLE
more restrictive scope for Google Drive

### ISSUE THREAD

**Issue by c64bob** [gilbertchen/duplicacy#555]
Would it be possible to limit the scope requested for Google Drive? For example, limit access of duplicacy to its application folder ([link](https://developers.google.com/drive/api/v2/appdata)). This way, duplicacy doesn't have access to what else is stored on my Google Drive.

**Comment by TheBestPessimist** [comment]
I don't like this idea because the folder duplicacy uses is _hidden from me_.

**Comment by c64bob** [comment]
Is manual access really needed? I thought all operations are performed through duplicacy.

**Comment by TheBestPessimist** [comment]
You may want for example to copy the storages via other syncing programs such as rclone. In this case you **need** the folder accessible normally.

You may also want to cleanup some snapshots: it is easier to delete those by hand and run a prune.

**Comment by gboudreau** [comment]
Instead of granting full read-write on all Google Drive, couldn't duplicacy use the scope `https://www.googleapis.com/auth/drive.file`, to get access only to the files and folders it created..?

> https://www.googleapis.com/auth/drive.file | View and manage Google Drive files and folders that you have opened or created with this app

Ref: https://developers.google.com/identity/protocols/googlescopes#docsv1

Changing the scope in the URL found on https://duplicacy.com/gcd_start, I get this prompt:
![image](https://user-images.githubusercontent.com/370329/55496949-3332aa00-560e-11e9-9dd4-1fbdafe206cf.png)

The problem I see right now is that duplicacy expects the specified folder (gcd://folder_here) to exist, and thus if we create it manually, the access token with the drive.file permission will not be able to access it... So we'd just need duplicacy to create the specified folder if it doesn't exist, and it should work. I'll see if I can test that myself using such a token, and adding a `mkdir()` in duplicacy's code...

**Comment by gboudreau** [comment]
Yes, that seems to work fine. I obtained a token with the `drive.file` permission instead of the `drive` permission, then changed `duplicacy_gcdstorage.go` to create the folder, if not found:

```diff
545c545,546
< 		return fmt.Errorf("Parent directory '%s' does not exist", parentDir)
---
> 		LOG_WARN("GCD_STORAGE", "Folder '%s' doesn't exist. Will create it in Google Drive's root folder.", dir)
> 		parentID = "root"
```

And I was able to successfully init and backup a test folder.

Not sure what side-effects creating the folder if it doesn't exist could have, as I don't know what it was like that before.

Let me know if I should send a PR with this change. Note that the URL used on https://duplicacy.com/gcd_start would need to be changed too, but I don't think that is part of this Github repo.

**Comment by gboudreau** [comment]
Sadly, when I tried to use the token with the `drive.file` scope on a folder that was created with an access token that used the `drive` scope, that failed. So users who would want to use the more restrictive `drive.file` scope would probably need to restart their backups from zero. (This would not affect new users.)

**Comment by c64bob** [comment]
> Let me know if I should send a PR with this change. Note that the URL used on https://duplicacy.com/gcd_start would need to be changed too, but I don't think that is part of this Github repo.

That would be great!

**Comment by TheBestPessimist** [comment]
@gboudreau 
>  So users who would want to use the more restrictive drive.file scope would probably need to restart their backups from zero.

Isn't it enough to copy the 3 folders inside the storage (`chunks`, `snapshots`, `config`) and the `config` file from old location to the new storage location?

Also: will this _way_ of doing things allow me to select a custom folder (eg. `gcd://my/very/extremly/long/path/to/the/storage/`) and also give me access (as the user) to copy (edit, delete, read with rclone, etc.) stuff into the storage folder "by hand" ?

**Comment by gboudreau** [comment]
> will this way of doing things allow me to select a custom folder (eg. gcd://my/very/extremly/long/path/to/the/storage/)
You can select a very deep folder, but your folders won't be created in the existing folders, unless they were created by duplicacy. (which is the point; duplicacy can't see the files & folders it didn't create.)
i.e. if you created a "my" folder in your Google Drive root manually (from the web UI for example), duplicacy will NOT see it, and create it's own "my" folder, in which it will create a "very" folder, and so on. So you'll end up with two "my" folders in your root. But if you want to do that to regroup your different backups in the same folders tree, that will work, as duplicacy will have created the folders for the 1st backup, and thus will be able to re-use the same folders for the second (and +) backups.

> and also give me access (as the user) to copy (edit, delete, read with rclone, etc.) stuff into the storage folder "by hand" ?
Yes. The created folders & files are visible on the drive.google.com website for example, and can be modified/deleted as any other normal files can.

**Comment by gboudreau** [comment]
@TheBestPessimist Indeed, continuing backups using an old storage folder works, by copying the old files & folders from the old storage dir (created manually) to a new folder that was created by duplicacy. I edited my post above with the details.

**Comment by c64bob** [comment]
> Let me know if I should send a PR with this change. 

@gboudreau Would you submit a PR with your change, or do you want me to do it? Thanks for your help with this issue!

**Comment by TheBestPessimist** [comment]
@gilbertchen do you agree with such a change?

**Comment by c64bob** [comment]
Well nevermind, I'm gonna go with restic.

**Comment by gboudreau** [comment]
Of note: Google will change its policy early next year for third-party apps to either use `drive.file`, or go through a certification process. Ref: [Enhancing security controls for Google Drive third-party apps ](https://cloud.google.com/blog/products/identity-security/enhancing-security-controls-for-google-drive-third-party-apps)
So migrating to `drive.file` will be needed by then, as I doubt going through the certification would be easy, or worth it.

**Comment by leohilbert** [comment]
A workaround that I found:

1. Create a new Google Account
2. Invite the new Account to your Google "Family" (https://families.google.com/families)
3. Enable sharing Google Drive-Space with your Family in https://one.google.com/settings
4. you now have a separate drive that you can create the token for. It does not have access to your personal drive, but shares the storage
