### ISSUE TITLE
Sparse-file support

### ISSUE THREAD

**Issue by pdf** [gilbertchen/duplicacy#68]
I don't see it documented whether or not this supports sparse files or xattrs?

**Comment by gilbertchen** [comment]
Duplicacy doesn't support sparse file operations, but extended attributes are backed up and restored.

**Comment by pdf** [comment]
Sparse file handling is pretty important, otherwise it's very easy to accidentally wedge a restore on ENOSPC when restoring large sparse files that did fit on the original disk

**Comment by ThomasWaldmann** [comment]
@gilbertchen comment of @pdf is right, this is pretty important. "overprovisioning" VM hosters using more capacity in sparse files than they actually have as disk space might have a bad day otherwise when they do a full restore.

You can pretty easily implement this, nothing special for backup is required, you can just check at restore time if it was a all-zero chunk and if so (and if sparse extraction is enabled), seek instead of write to the destination file.

**Comment by gilbertchen** [comment]
Nice to see the borg developer here!  Thank you for the suggestion.

Duplicacy almost has full sparse file support.  In a restore operation, if there is an existing file that is sparse, then Duplicacy will preserve the sparseness.  This is because Duplicacy reads the existing file first and skips chunks that don't change.  Therefore, the only thing that needs to be done is to create an empty sparse file if the file to be restored does not exist.

You can manually create the empty sparse file if you need to restore a sparse file with the current version.  The following command is borrowed from http://prefetch.net/blog/index.php/2009/07/05/creating-sparse-files-on-linux-hosts-with-dd :
```
dd if=/dev/zero of=xen-guest.img bs=1 count=0 seek=8G  
```

**Comment by gilbertchen** [comment]
With https://github.com/gilbertchen/duplicacy/commit/d881ac9169ab7aaf422c978775624cc43e4e4f9d Duplicacy now fully supports restore of sparse files.
