### ISSUE TITLE
The file has a size of X but total size of chunks is 0

### ISSUE THREAD

**Issue by chaseadam** [gilbertchen/duplicacy#90]
exact error: The snapshot contains an error: The file git/NookManager/staging/build/nook_src/distro/kernel/.git/objects/66/1f0d877bd13cdf9938ab49fc1fabcf589e7ca1 has a size of 16041 but the total size of chunks is 0.

Actual file  is reported as 16041 via "ls"

The storage is format pre-1.2.0 in backblaze.

**Comment by gilbertchen** [comment]
Did you get this during a backup?

Which platform are you running Duplicacy on?  I can get you a customized build that prints our more info for this error.

**Comment by chaseadam** [comment]
This was during a backup on Fedora 25 with binary: duplicacy_linux_x64_2.0.4

**Comment by gilbertchen** [comment]
Do you happen to keep logs for this backup and the previous one?  One possibility I can think is that the previous backup wasn't completed due to an error or an interrupt, and this backup resumed from the incomplete backup.  This error may be caused by a bug in the fast resuming feature we introduced in 2.0.4.

**Comment by chaseadam** [comment]
It is possible there was an interrupted backup. I am happy to use a version with more debugging. I have yet to successfully backup this <snapshot id>.

Not sure where the logs are stored, but the output is usually just "packed" repeated multiple times with the filenames. Should I try removing my incomplete snapshot? I see this in my log "Incomplete snpashot loaded from /home/<uid>/.duplicacy/incomplete"

I tried to ignore the offending directory, but ran into this again with a different file (.wine/drive_c/windows/system32/d3dx9_38.dll)

**Comment by gilbertchen** [comment]
Is it okay to send that file (/home//.duplicacy/incomplete) to me?  This is definitely a bug in the fast resuming implementation.  I can double check the code path but that file may have useful info.

You can just delete this file and run a new backup.

**Comment by chaseadam** [comment]
The file is a bit large (300MB). Do you have a GPG key I can encrypt the link with?

**Comment by gilbertchen** [comment]
I'll try to reproduce it myself.

**Comment by gilbertchen** [comment]
Release 2.0.5 should fix this bug.  It was caused by some files that had been uploaded leaking into the incomplete snapshot, thus the discrepancy between the file size and the total size of chunks.

If you want to build it yourself, you should take https://github.com/gilbertchen/duplicacy/commit/2908b807b95fb8f1272d2ddab26c9ecbcc142f1d.  I messed up the commit for this fix and there was a file missing.
